# Generated by Django 5.2.11 on 2026-02-10 13:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_submission'),
        ('modules', '0005_resourceprogress_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('user', 'module')},
        ),
    ]
