# Generated by Django 5.2.11 on 2026-02-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
