# Generated by Django 5.2.11 on 2026-02-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_module_assignment_prompt_module_has_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
