# Generated by Django 5.2.11 on 2026-02-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_resourceprogress_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourceprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resourceprogress',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resourceprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='module',
            name='assignment_prompt',
        ),
        migrations.RemoveField(
            model_name='module',
            name='has_assignment',
        ),
        migrations.RemoveField(
            model_name='module',
            name='has_quiz',
        ),
        migrations.RemoveField(
            model_name='module',
            name='priority',
        ),
        migrations.AddField(
            model_name='module',
            name='week',
            field=models.PositiveIntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1),
        ),
        migrations.DeleteModel(
            name='ModuleProgress',
        ),
        migrations.DeleteModel(
            name='ResourceProgress',
        ),
    ]
