# Generated by Django 5.2.11 on 2026-02-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_resourceprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['week', 'id']},
        ),
    ]
