# Generated by Django 5.2.11 on 2026-02-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_alter_module_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assignment_prompt',
            field=models.TextField(blank=True, help_text='Instructions for the module assignment'),
        ),
    ]
